# Generated by Django 6.0 on 2026-01-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'permissions': [('request_bill', 'request bill')]},
        ),
    ]
