# Generated by Django 6.0 on 2026-01-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
