# Generated by Django 6.0 on 2026-01-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='is_sent_alert',
            field=models.BooleanField(default=False),
        ),
    ]
